name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter  
      run: npm run lint:check
    
    - name: Check formatting
      run: npm run format:check
    
    - name: Run tests
      run: npm run test:run

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build:prod
      env:
        # Use fake values for build test
        VITE_FIREBASE_API_KEY: test_key
        VITE_FIREBASE_AUTH_DOMAIN: test.firebaseapp.com
        VITE_FIREBASE_PROJECT_ID: test_project
        VITE_FIREBASE_STORAGE_BUCKET: test.appspot.com
        VITE_FIREBASE_MESSAGING_SENDER_ID: "123456789"
        VITE_FIREBASE_APP_ID: test_app_id
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 30